class EmailChange < ApplicationRecord
  EXPIRED_TIME: ActiveSupport::Duration

  attr_accessor change_token: String

  def match?: (String) -> TrueClass

  def self.new_token: () -> String

  def self.digest: (String) -> String

  def create_change_digest: () -> void
end