class PasswordReset < ApplicationRecord
  EXPIRED_TIME: ActiveSupport::Duration

  attr_accessor reset_token: String

  def match?: (String) -> TrueClass

  def self.new_token: () -> String

  def self.digest: (String) -> String

  def create_reset_digest: () -> void
end