AWSTemplateFormatVersion: '2010-09-09'
Description: 既存インフラ利用・app-base Fargateサービス＆ALBルール最小テンプレ

Parameters:
  AppName:
    Type: String
    # Default: app-base
  AppImageUri:
    Type: String
    Default: !Sub "435917083888.dkr.ecr.ap-northeast-1.amazonaws.com/workshop-app/prod/${AppName}:latest"
  AppPort:
    Type: Number
    # Default: 3000
  HostName:
    Type: String
    # Default: appbase.workshop-app.net
  ListenerRulePriority:
    Type: Number
    value: 100    

  # 既存リソース
  ECSClusterName:
    Type: String
    Default: workshop-app-prod-cluster
  SubnetIds:
    Type: CommaDelimitedList
    Default: "subnet-007a22c02b8945a19,subnet-0c1f81ed39188b773"
  FargateSgId:
    Type: String
    Default: sg-074598d362d105f42
  AlbListenerArn:
    Type: String
    Default: arn:aws:elasticloadbalancing:ap-northeast-1:435917083888:listener/app/workshop-app-prod-alb/7aa0910a0c85959e/afe92482bb237c19
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0f9bfe9c5d7e23930

  # SSM Parameter Store（Secrets）ARN
  DatabaseUrlArn:
    Type: String
    # Default: arn:aws:ssm:ap-northeast-1:435917083888:parameter/app_base/prod/DATABASE_URL
  CacheDatabaseUrlArn:
    Type: String
    # Default: arn:aws:ssm:ap-northeast-1:435917083888:parameter/app_base/prod/CACHE_DATABASE_URL
  QueueDatabaseUrlArn:
    Type: String
    # Default: arn:aws:ssm:ap-northeast-1:435917083888:parameter/app_base/prod/QUEUE_DATABASE_URL
  RailsMasterKeyArn:
    Type: String
    # Default: arn:aws:ssm:ap-northeast-1:435917083888:parameter/app_base/prod/RAILS_MASTER_KEY

Resources:
  # CloudWatch Logs Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${AppName}"
      RetentionInDays: 7

  # ECS Task Execution Role
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-execution-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SSMParameterAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameters
                  - ssm:GetParameter
                Resource:
                  - !Ref DatabaseUrlArn
                  - !Ref CacheDatabaseUrlArn
                  - !Ref QueueDatabaseUrlArn
                  - !Ref RailsMasterKeyArn

  # ECS Task Role
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}-task-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${AppName}-tg"
      VpcId: !Ref VpcId
      Port: !Ref AppPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'

  AppListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref AlbListenerArn
      Priority: !Ref ListenerRulePriority
      Actions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref AppTargetGroup
                Weight: 100
      Conditions:
        - Field: host-header
          Values:
            - !Ref HostName

  AppTaskDef:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${AppName}-task-def"
      Cpu: '1024'
      Memory: '3072'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRole
      TaskRoleArn: !Ref TaskRole
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      EphemeralStorage:
        # FargateのEphemeralStorageはデフォルトで20GiB
        SizeInGiB: 25
      ContainerDefinitions:
        - Name: !Ref AppName
          Image: !Ref AppImageUri
          Essential: true
          StartTimeout: 120
          StopTimeout: 30
          PortMappings:
            - Name: !Sub "${AppName}-3000-tcp"
              ContainerPort: !Ref AppPort
              HostPort: !Ref AppPort
              Protocol: tcp
              AppProtocol: http
          Environment:
            - Name: RAILS_LOG_TO_STDOUT
              Value: "true"
            - Name: RAILS_ENV
              Value: production
            - Name: RAILS_SERVE_STATIC_FILES
              Value: "true"
          Secrets:
            - Name: CACHE_DATABASE_URL
              ValueFrom: !Ref CacheDatabaseUrlArn
            - Name: DATABASE_URL
              ValueFrom: !Ref DatabaseUrlArn
            - Name: QUEUE_DATABASE_URL
              ValueFrom: !Ref QueueDatabaseUrlArn
            - Name: RAILS_MASTER_KEY
              ValueFrom: !Ref RailsMasterKeyArn
          Ulimits:
            - Name: nofile
              SoftLimit: 65536
              HardLimit: 65536
            - Name: nproc
              SoftLimit: 4096
              HardLimit: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
              mode: non-blocking
              awslogs-create-group: "true"
              max-buffer-size: 25m

  AppService:
    Type: AWS::ECS::Service
    DependsOn: 
      - AppListenerRule
      - AppTargetGroup
    Properties:
      ServiceName: !Sub "${AppName}-service"
      Cluster: !Ref ECSClusterName
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref AppTaskDef
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: [!Ref FargateSgId]
      LoadBalancers:
        - TargetGroupArn: !Ref AppTargetGroup
          ContainerName: !Ref AppName
          ContainerPort: !Ref AppPort

Outputs:
  ServiceName:
    Description: ECS Service Name
    Value: !Ref AppService
  TargetGroupArn:
    Description: Target Group ARN
    Value: !Ref AppTargetGroup
  TaskDefinitionArn:
    Description: Task Definition ARN
    Value: !Ref AppTaskDef
  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref LogGroup
